name = "vhlink"
type = "javascript"
account_id = "39a76d640a29996bffbd58c36a537c2b"
workers_dev = true
route = ""
zone_id = ""
kv_namespaces = [
  { binding = "LINKS", id = "8d19a50dd8cc494a80ffb9ffb8ccf566", preview_id = "8d19a50dd8cc494a80ffb9ffb8ccf566" }
]
